# Generated by Django 4.2.3 on 2023-08-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_manufacture_date',
            field=models.DateField(null=True),
        ),
    ]
