# Generated by Django 4.2.3 on 2023-08-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='course_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='course_fee',
            field=models.BigIntegerField(null=True),
        ),
    ]
