# Generated by Django 4.2.3 on 2023-09-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0002_cartmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='vendor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
