# Generated by Django 4.2.3 on 2023-09-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0003_productmodel_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
