# Generated by Django 4.2.3 on 2023-09-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0007_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='original_price',
            field=models.BigIntegerField(null=True),
        ),
    ]
